### ISSUE TITLE
Inverting a matrix

### ISSUE THREAD

**Issue by angusgibbs** [angusgibbs/matrix#1]
Currently you cannot invert a matrix. I am working on an implementation that will invert a 2 by 2 or 3 by 3 matrix, but I have yet to find a good solution for inverting a n by n matrix.

**Comment by aashay** [comment]
Found your repo while perusing various node matrix math repos.  

http://sylvester.jcoglan.com/api/matrix.html#inverse uses Gauss-Jordan Elimination (http://mathworld.wolfram.com/Gauss-JordanElimination.html) so that might be an option.

**Comment by angusgibbs** [comment]
Thanks for the link! Hopefully I'll have time to implement this this weekend.
